# Generated by Django 3.2.8 on 2022-05-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_currency', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
