# Generated by Django 3.2.8 on 2022-05-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220517_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='current_currency',
            field=models.IntegerField(),
        ),
    ]
