# Generated by Django 3.2.8 on 2022-05-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_mainpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cover_1', models.FileField(upload_to='post')),
                ('cover_2', models.FileField(upload_to='post')),
                ('cover_3', models.FileField(upload_to='post')),
            ],
        ),
        migrations.DeleteModel(
            name='MainPost',
        ),
    ]
