# Generated by Django 3.2.8 on 2022-05-18 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220518_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover_1',
            new_name='first',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='cover_2',
            new_name='second',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='cover_3',
            new_name='third',
        ),
    ]
