# Generated by Django 3.2.8 on 2022-05-19 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220519_0526'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
