# Generated by Django 3.2.8 on 2022-05-19 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
