# Generated by Django 3.2.8 on 2022-05-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('cover', models.FileField(upload_to='product/cover/<int:pk>')),
                ('cover_first', models.FileField(upload_to='product/cover/<int:pk>')),
                ('cover_second', models.FileField(upload_to='product/cover/<int:pk>')),
                ('size', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('somoni', models.BooleanField()),
                ('ruble', models.BooleanField()),
                ('discription', models.TextField()),
            ],
        ),
    ]
