# Generated by Django 3.2.8 on 2022-05-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.FileField(upload_to='product/cover'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_first',
            field=models.FileField(upload_to='product/cover'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_second',
            field=models.FileField(upload_to='product/cover'),
        ),
    ]
